# Example setups come from the SeisSol training material (https://github.com/SeisSol/Training)
# and the SeisSol examples (https://github.com/SeisSol/Examples), both BSD-3-Clause, created by the
# SeisSol team. data/examples.toml pins every file of every example (path, size, git blob SHA-1)
# at a fixed commit; it is generated by tools/generate_examples_manifest.jl.
const MANIFEST_FILE = joinpath(@__DIR__, "..", "data", "examples.toml")
include_dependency(MANIFEST_FILE)
const EXAMPLES = Dict{String,Dict{String,Any}}(e["name"] => e for e in TOML.parsefile(MANIFEST_FILE)["example"])

# Description of the status field of an example
const STATUS = Dict(
    "runs" => "works with the bundled SeisSol binary",
    "unverified" => "not verified to work with the bundled binary",
    "needs-asagi" => "needs a SeisSol binary with ASAGI (3D structure read from NetCDF files)",
    "needs-mesh" => "mesh is not included: generate it with gmsh and PUMGen",
)

# Fix-ups of files that refer to things missing from the example repositories.
const FIXUPS = Dict{String,Function}(
    # the record-point file that the parameter file names is not part of the repository
    "tpv13" => par -> delete_parameter!(par, "RFileName"),
)

is_doc(path) = occursin(r"(^|/)figures/|\.(png|ipynb|pdf)$"i, path)

"""
    examples(; status=nothing)

Names of the examples that can be fetched with [`download_example`](@ref). Examples of the
SeisSol training material are called `"tpv13"`, `"kaikoura"`, ...; the setups in the SeisSol
examples repository are called `"examples/tpv5"`, ... With `status` (`"runs"`, `"unverified"`,
`"needs-asagi"` or `"needs-mesh"`) only the examples with that status are returned.
"""
function examples(; status = nothing)
    names = sort!(collect(keys(EXAMPLES)))
    status === nothing && return names
    return filter(n -> EXAMPLES[n]["status"] == status, names)
end

"""
    example_info(name; io=stdout)

Print description, status, size and files of an example.
"""
function example_info(name::AbstractString; io::IO = stdout)
    ex = get(EXAMPLES, name, nothing)
    ex === nothing && throw(ArgumentError("unknown example \"$name\"; available: $(examples())"))
    files = ex["files"]
    mb(f) = sum(x["size"] for x in f; init = 0) / 1e6
    println(io, name, " (", ex["repo"], "/", ex["folder"], ")")
    println(io, "  ", ex["description"])
    println(io, "  status:  ", ex["status"], " - ", STATUS[ex["status"]])
    println(io, "  parfile: ", ex["parfile"])
    @printf(io, "  size:    %.1f MB (%d files), without figures/notebooks: %.1f MB\n",
            mb(files), length(files), mb(filter(f -> !is_doc(f["path"]), files)))
    return nothing
end

git_blob_sha1(data::AbstractVector{UInt8}) = bytes2hex(sha1(vcat(codeunits("blob $(length(data))\0"), data)))

"""
    download_example(name; dir=mktempdir(), docs=false) -> parfile

Download the example `name` (see [`examples`](@ref) and [`example_info`](@ref)) into `dir` and
return the path of its main parameter file. Every file is verified against the checksum pinned
in the package. Figures, notebooks and PDFs are skipped unless `docs=true`.

Only the examples with status `"runs"` are known to work with the bundled generic SeisSol
binary; for the others a warning explains what is missing.

```julia
par = download_example("tpv13")
set_parameters!(par; EndTime = 1.0)
run_seissol(par; nprocs = 2)
```
"""
function download_example(name::AbstractString; dir::AbstractString = mktempdir(), docs::Bool = false)
    haskey(EXAMPLES, name) || throw(ArgumentError("unknown example \"$name\"; available: $(examples())"))
    ex = EXAMPLES[name]
    ex["status"] == "runs" || @warn "Example \"$name\": $(STATUS[ex["status"]]) - $(ex["description"])"
    files = filter(f -> docs || !is_doc(f["path"]), ex["files"])
    @info "Downloading example \"$name\" ($(round(sum(f["size"] for f in files) / 1e6; digits = 1)) MB, $(length(files)) files) to $dir"
    mkpath(dir)
    base = "https://raw.githubusercontent.com/$(ex["repo"])/$(ex["commit"])"
    for f in files
        local_path = joinpath(dir, split(f["path"], '/'; limit = 2)[2])
        mkpath(dirname(local_path))
        Downloads.download("$base/$(f["path"])", local_path)
        data = read(local_path)
        (length(data) == f["size"] && git_blob_sha1(data) == f["sha1"]) ||
            error("checksum mismatch for $(f["path"]); delete $dir and try again")
    end
    par = joinpath(dir, ex["parfile"])
    haskey(FIXUPS, name) && FIXUPS[name](par)
    return isempty(ex["parfile"]) ? dir : par
end
